CREATE TABLE `article` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT "id",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
  `column_id` BIGINT UNSIGNED NOT NULL COMMENT "所属栏目",
  `title` VARCHAR(64) NOT NULL COMMENT "文章标题",
  `content` TEXT NOT NULL COMMENT "文章内容",
  `priority` INT NOT NULL DEFAULT -1 COMMENT "文章显示优先级，置顶",
  `creater_uid` BIGINT UNSIGNED NOT NULL COMMENT "创建人id",
  `updater_uid` BIGINT UNSIGNED NOT NULL COMMENT "最近修改人id",
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;