CREATE TABLE `column` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT "id",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "创建时间",
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新时间",
  `name` VARCHAR(64) NOT NULL COMMENT "栏目名称",
  `creater_uid` BIGINT UNSIGNED NOT NULL COMMENT "创建人id",
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;